packages/button/README.md
packages/card/README.md
packages/fab/README.md
packages/floating-label/README.md
packages/line-ripple/README.md
packages/material-icon/README.md
packages/notched-outline/README.md
packages/ripple/README.md
packages/top-app-bar/README.md

Updated the descriptions to be more consistent.

docs: update descriptions

---

.gitignore
docs/release.md
scripts/release/pre-release.sh

feat: Added changelog.md

---

.travis.yml

Due to screenshot testing updates, git pull should happen after checking out a branch

fix: travis and docker integration

---

packages/line-ripple/index.js
test/unit/line-ripple/index.test.js

fix(line-ripple): Convert style name to camel case

---

packages/text-field/Input.js
test/unit/text-field/Input.test.js

fixes https://github.com/material-components/material-components-web-react/issues/165

fix(text-field): move handleValueChange call when this.props.value updates

---

packages/text-field/README.md

There is a typo in the example code.

docs: Update README.md

---

packages/chips/Chip.js
packages/floating-label/index.js
packages/line-ripple/index.js
packages/notched-outline/index.js
packages/ripple/index.js
packages/text-field/helper-text/index.js
packages/text-field/icon/index.js
packages/text-field/index.js
packages/top-app-bar/index.js

fixes https://github.com/material-components/material-components-web-react/issues/175

fix: point packages to MDC Web /dist ES5 files

---

packages/ripple/index.js
test/unit/ripple/index.test.js

fix(ripple): add test to avoid computeBoundingRect error

---

.travis.yml

Tests are failing when they do locally, which leads me to believe its a timeout issue.

fix(infrastructure): increase screenshot timeout

---

packages/text-field/helper-text/README.md

docs(text-field): Add HelperText Validity Usage Docs

---

ROADMAP.md
packages/tab-bar/index.js
packages/tab/TabRipple.js
packages/tab/index.js
test/unit/tab/index.test.js

fix(tab-bar): Arrow keys should focus adjacent tab

---

package-lock.json
packages/chips/Chip.js
packages/chips/ChipSet.js
test/unit/chips/Chip.test.js
test/unit/chips/ChipSet.test.js

Partial fix to: 
- https://github.com/material-components/material-components-web-react/issues/269.
- https://github.com/material-components/material-components-web-react/issues/268 
This is still waiting on MDC Web fixes before #269 can be completed.
Dependencies:
- https://github.com/material-components/material-components-web/issues/3612
- https://github.com/material-components/material-components-web/issues/3613
- https://github.com/material-components/material-components-web/issues/3615

fix(chips): use notifyRemoval and notifyInteraction adapter methods

---

package-lock.json
package.json
packages/line-ripple/index.js
test/screenshot/text-field/index.js
test/unit/line-ripple/index.test.js

fixes https://github.com/material-components/material-components-web-react/issues/275

fix(line-ripple): stop calling foundation.setRippleCenter when argument is NaN

---

package.json

fixes https://github.com/material-components/material-components-web-react/issues/283

fix(infrastructure): speed up prerelease script

---

package-lock.json
packages/chips/Chip.js
packages/chips/README.md
packages/chips/package.json

fixes https://github.com/material-components/material-components-web-react/issues/298

fix(chips): replace relative path with npm package

---

package.json
packages/icon-button/package.json

https://github.com/material-components/material-components-web-react/issues/299

fix(icon-button): add main field to package.json

---

packages/button/index.js

refactor(button): convert button to SFC

---

packages/icon-button/IconToggle.js
packages/icon-button/index.js
packages/icon-button/index.scss

Add MIT License to some icon button files.

fix(icon-button): add MIT license to files

---

test/unit/menu-surface/index.test.js

related https://github.com/material-components/material-components-web-react/pull/295/files/d4576483a5b86102622b69c18c3875de6394d1ec#diff-94120e1696cf7be2b63afd23e1514ac6

fix(menu-surface): fix menu surface unit test typo

---

README.md

updating from travis.org --> travis.com

fix(infrastructure): fix travis badge on readme

---

README.md
docs/adding-env-variables.md
docs/create-react-app-v1.md

fixes https://github.com/material-components/material-components-web-react/issues/326 and https://github.com/material-components/material-components-web/issues/3985

docs: update main README with CRA2 guidelines

---

package-lock.json
packages/text-field/Input.js
packages/text-field/README.md
packages/text-field/index.js
test/unit/text-field/Input.test.js
test/unit/text-field/index.test.js

fix(text-field): added reference to input element

---

packages/tab-indicator/README.md

found a missing import statement in the example

docs(tab-indicator): readme update

---

package-lock.json
package.json
packages/linear-progress/.npmignore
packages/linear-progress/README.md
packages/linear-progress/index.js
packages/linear-progress/index.scss
packages/linear-progress/package.json
test/screenshot/linear-progress/index.js
test/screenshot/linear-progress/index.scss
test/unit/linear-progress/index.test.js

feature(linear-progress): add component

---

.travis.yml
package-lock.json
packages/button/.npmignore
packages/card/.npmignore
packages/checkbox/.npmignore
packages/chips/.npmignore
packages/fab/.npmignore
packages/floating-label/.npmignore
packages/icon-button/.npmignore
packages/layout-grid/.npmignore
packages/line-ripple/.npmignore
packages/linear-progress/.npmignore
packages/list/.npmignore
packages/material-icon/.npmignore
packages/menu-surface/.npmignore
packages/notched-outline/.npmignore
packages/radio/.npmignore
packages/ripple/.npmignore
packages/select/.npmignore
packages/switch/.npmignore
packages/tab-bar/.npmignore
packages/tab-indicator/.npmignore
packages/tab-scroller/.npmignore
packages/tab/.npmignore
packages/text-field/.npmignore
packages/top-app-bar/.npmignore
packages/typography/.npmignore

fixes https://github.com/material-components/material-components-web-react/issues/466

chore(infrastructure): remove all .npmignores

---

packages/tab/README.md

From discussion on issue #505.

Include tab-indicator with Tab documentation.

---

packages/checkbox/README.md

Since it's JSX I don't think you can use "for". Some details are here:
https://github.com/facebook/react/issues/1819

Use htmlFor in example in Checkbox docs.

---

.travis.yml
packages/checkbox/README.md

fixes broken readme example in checkbox

docs(checkbox): fix example

---

packages/top-app-bar/index.tsx

fix(top-app-bar): make top app bar props optional

---

packages/switch/README.md

related https://github.com/material-components/material-components-web-react/pull/586

docs(switch): update broken readme

---

packages/top-app-bar/README.md

fixes https://github.com/material-components/material-components-web-react/issues/603

docs: Update Top App Bar README.md

---

packages/text-field/README.md

The current code doesn't compile.
Need to use currentTarget instead of target (because target is generic now)

fix(text-field) fix example compilation issue

---

packages/select/index.tsx
test/unit/select/index.test.tsx

successful merge should close #727
---
I signed it

fix(select): pass state.value to NativeControl as prop.value

---

packages/text-field/Input.tsx
packages/text-field/helper-text/index.tsx
packages/text-field/index.tsx

https://github.com/material-components/material-components-web-react/issues/732
related https://github.com/material-components/material-components-web-react/issues/734

fix(text-field): make props optional

---

packages/ripple/index.tsx

My bad, I listened typescript type suggestions, fixed. Will not use ClientRect anymore

fix(ripple): ClientRect => defaultrect object

---

packages/drawer/README.md

docs(drawer): fix typo in readme

---

package-lock.json
package.json
packages/menu-surface/index.tsx
packages/menu-surface/package.json
test/unit/menu-surface/index.test.tsx

Continuation of https://github.com/material-components/material-components-web-react/pull/762 -- this is out of sync with the base branch.
related: #697

feat(menu-surface): upgrade to mdc web v1

---

package-lock.json
package.json
packages/fab/package.json

fix(fab): upgrade to mdc-web v1.1

---

package-lock.json
package.json
packages/linear-progress/index.tsx
packages/linear-progress/package.json
test/unit/linear-progress/index.test.tsx

fix(linear-progress): upgrade mdc-web to v1

---

packages/top-app-bar/index.tsx
test/unit/chips/ChipSet.test.tsx
test/unit/text-field/index.test.tsx
test/unit/top-app-bar/index.test.tsx

 fix(top-app-bar): change scrollTop to offsetTop in getViewportScrollY

---

packages/chips/package.json
test/unit/list/index.test.tsx

Fixes #301 
I signed it!
I confirmed that there is no additional features from v1.0.0 to v1.1.1
So I just update dependency!

 fix(chips): Fix incorrect ripple effect

---

packages/dialog/package.json
packages/top-app-bar/package.json

Ensure all package.json files have a link to the repo

---

package-lock.json
package.json

Fixes postinstall from failing npm install

fix(infrastructure): fix postinstall

---

packages/floating-label/index.tsx

feat(floating-label): change literal to constant

---

packages/layout-grid/Cell.tsx
packages/layout-grid/Grid.tsx
packages/layout-grid/Row.tsx
packages/layout-grid/constant.ts

 feat(layout-grid): define CSS_CLASSES & DEVICE_TYPE

---

packages/fab/constant.ts
packages/fab/index.tsx

chore(fab): define CSS_CLASSES

---

packages/button/constant.ts
packages/button/index.tsx

related to https://github.com/material-components/material-components-web-react/issues/827

feat(button): define CSS_CLASSES

---

packages/text-field/README.md

Update textfield docs

---

package-lock.json
package.json
packages/checkbox/package.json

chore(checkbox): upgrade to mdcw 2.x

---

package-lock.json
package.json
packages/dialog/package.json

chore(dialog): upgrade to mdcw 2.x

---

package-lock.json
package.json
packages/fab/package.json

chore(fab): upgrade to mdcw 2.x

---

package-lock.json
package.json
packages/icon-button/package.json

chore(icon-button): upgrade to mdcw 2.x

---

packages/list/package.json

fixes https://github.com/material-components/material-components-web-react/issues/901

fix(list): update checkbox and radio deps

---

packages/select/README.md

Update select README.md

---

README.md
package.json
packages/menu/README.md
packages/select/README.md

fixes https://github.com/material-components/material-components-web-react/issues/926

docs: update menu/select styles and add snackbar to main readme

---

packages/button/package.json
packages/card/package.json
packages/checkbox/package.json
packages/chips/package.json
packages/dialog/package.json
packages/drawer/package.json
packages/fab/package.json
packages/floating-label/package.json
packages/icon-button/package.json
packages/layout-grid/package.json
packages/line-ripple/package.json
packages/linear-progress/package.json
packages/list/package.json
packages/material-icon/package.json
packages/menu-surface/package.json
packages/menu/package.json
packages/notched-outline/package.json
packages/radio/package.json
packages/ripple/package.json
packages/select/package.json
packages/snackbar/package.json
packages/switch/package.json
packages/tab-bar/package.json
packages/tab-indicator/package.json
packages/tab-scroller/package.json
packages/tab/package.json
packages/text-field/package.json
packages/top-app-bar/package.json
packages/typography/package.json

Fixes material-components/material-components-web-react#616

Made react a peer dependency for all packages.

---

package-lock.json
package.json
packages/text-field/index.tsx
packages/text-field/package.json
test/screenshot/golden.json
test/screenshot/text-field/TestTextField.tsx
test/screenshot/text-field/noLabel.tsx
test/screenshot/text-field/variants.tsx
test/unit/text-field/index.test.tsx

related to #224
Reopening of #840, since that was targeting an old feature branch.

feat(text-field): add placeholder property

---

packages/dialog/package.json
scripts/directory-reader.js
scripts/package-json-reader.js
scripts/package-name-converter.js
scripts/release/cp-pkgs.js
scripts/release/verify-pkg-main.js
test/unit/menu/MenuList.test.tsx
tsconfig.json

- fix lint/compile error
- set "declarationDir" in tsconfig
- add "types" property in dialog
- add validate code that to check existence of definition file

 fix(infrastructure): types generated directory problem

---

packages/list/index.tsx
test/unit/list/index.test.tsx

feat(list): Implement getAttributeForElementIndex

---

packages/webpack.config.js

fixes https://github.com/material-components/material-components-web-react/issues/954

fix(infrastructure): fix SSR support for webpack4 update

---

packages/chips/README.md

fix(chips): fix InputChips example error

---

examples/catalog/src/content/chips/ChipsExample.tsx

fix(example): chips need unique key

---

.eslintignore

fix(infrastructure): add eslint ignore lines
