material-components/material-components-web-react

package-lock.json
package.json

Upgrading due to material-components/material-components-web-codelabs#30. Enables `npm install` to work on platforms without python installed.

chore: update node-sass to 4.9

---

package.json
packages/button/index.scss
packages/card/index.scss
packages/floating-label/index.scss
packages/line-ripple/index.scss

Hi, I would like to help with material-components-web-react.
The sass imports are handy, but I was having trouble importing SCSS from Button. I needed to directly import the css from the non-react package, basically duplicating the intent of the index.scss of react-button:
When I looked at [the icon component sass import](https://github.com/material-components/material-components-web-react/blob/a45c75a1fd8bc7b83fbe0775fc629c928bb1df0f/packages/material-icon/index.scss#L2) I noticed that it didn't have an extension. Going into node_modules and removing it from the button index.scss file fixed the issue and allowed me to just import the button styles with `@import "@material/button/mdc-button";`, so perhaps this was just an oversight.
I've never used learn before, so I may need help …

Remove scss extensions from @material/mdc-* imports

---

packages/ripple/index.js
test/unit/ripple/index.test.js

Fixes #41.
Re-implement the `isSurfaceActive()` adapter method to check for active state directly on the ripple surface element, instead of creating and updating an `isActivated` state variable. 
Wire up the appropriate event handlers to call `deactivate(e)` in the foundation.

fix(ripple): Trigger on key events

---

packages/webpack.config.js

fixes https://github.com/material-components/material-components-web-react/issues/82
Error occurs when an empty directory exists in /packages ie. Chips.

fix(infrastructure): fixed npm run build error for empty package directories

---

docs/getting-started.md

Addresses comments from #70 (https://github.com/material-components/material-components-web-react/issues/70#issuecomment-395233160).

docs: update getting-started.md to follow create-react-app recommended approach for sass imports

---

package-lock.json
package.json
packages/button/package.json
packages/card/package.json
packages/fab/package.json
packages/floating-label/package.json
packages/line-ripple/package.json
packages/material-icon/package.json
packages/notched-outline/package.json
packages/ripple/package.json
packages/text-field/package.json
packages/top-app-bar/package.json
packages/webpack.config.js
scripts/release/cp-pkgs.js

feat(infrastructure): default npm entry point to ES5

---

docs/getting-started.md

modified:   docs/getting-started.md
The -o option of node-sass-chokidar is for output directory. For import './App.css' to work in App.js, in build-css script it should be -o ./src otherwise a directory named App.css is created an App.css file is created inside it.

docs: build-css script, edit for output directory.

---

docs/getting-started.md

Fixed a small typo.
From "The difference being all the your node_modules imports will..."
To "The difference being all the node_modules imports will..."

Fix getting-started typo

---

.travis.yml
test/screenshot/top-app-bar/fixed.html
test/screenshot/top-app-bar/prominent.html
test/screenshot/top-app-bar/short.html
test/screenshot/top-app-bar/standard.html

A few top app bar screenshot tests were missing material icon imports in the html files. This caused failures in the screenshot tests.

fix(top-app-bar): add material icon imports in screenshot tests

---

README.md

fixes https://github.com/material-components/material-components-web-react/issues/205

docs: add tab indicator to main readme page

---

packages/webpack.config.js

When we converted all our @ material package imports to point to the es5 files instead of the es6, this changed the filepaths. We also need to update the webpack external filepaths so it is not included in bundled javascript file.

fix(infrastructure): add the es5 @material/package/dist/mdc.package to externals

---

packages/text-field/README.md

Documentation states that it Sass imports should be included for styling floating label, line ripple and notched outline. However, they are already imported when `mdc-textfield` styles are imported (https://github.com/material-components/material-components-web/blob/master/packages/mdc-textfield/mdc-text-field.scss#L24-L26)  from  text-field `index.scss` (https://github.com/material-components/material-components-web-react/blob/master/packages/text-field/index.scss#L25).

docs: remove obsolete Style section in text-field

---

packages/chips/ChipSet.js
packages/chips/README.md
test/screenshot/chips/index.js
test/unit/chips/ChipSet.test.js

Removes the responsibility of removing the chip from the user into the component. Instead of having a handleRemove prop method, I renamed to chipsUpdate which is passed an array of chip props.

fix(chips): remove handleRemove method for chipsUpdate method

---

packages/tab/README.md

The package is `@material/react-material-icon` not `@material/material-icon`

Corrected imports of "MaterialIcon" component

---

packages/list/index.js
test/unit/list/index.test.js

As you know, 0 is replaced with false in javascript.
When selectedIndex is 0, setSelectedIndex is not executed.
So I add check code "Number.isInteger".

fix(list): selectedIndex 0 isn't working

---

packages/select/README.md

See that the erased text is the same description of the next row.

docs(select): Removed empty row in props documentation

---

packages/card/README.md

Hello, have been enjoying this awesome library you have here. As @moog16 had stated in issue #503 a `<CardMedia>` component must have an aspect ratio passed into it in order for it to display. I want to clarify the documentation to reflect that important detail. Thanks! 😃

docs(card-media): update readme with aspect ratio requirement

---

.travis.yml
packages/list/index.js

#492 
I didn't have a chance to test this - please do so before merging

fix(list): minification-safe element type comparison

---

docs/contributions/running-tests.md

[running-tests.md](https://github.com/material-components/material-components-web-react/blob/master/docs/contributions/running-tests.md) referenced screenshot tests, but the filename was misspelled. 
---
I signed it.

docs: update broken look to ../screenshot-tests.md

---

packages/top-app-bar/README.md
packages/top-app-bar/index.js
test/screenshot/golden.json
test/screenshot/top-app-bar/dense.js
test/screenshot/top-app-bar/prominentDense.js
test/screenshot/top-app-bar/variants.js
test/unit/top-app-bar/index.test.js

adds missing dense variant. See issue #518. As noted on discord I am having trouble getting screenshot testing to run. But I did add two. A `TopAppBarDense` and a `TopAppBarProminetDense`. Both will be modified further in an additional PR that adds the correct class to `<TopAppBarFixedAdjust>`
---
I signed it.

feat(top app bar): dense variant

---

packages/button/package.json
packages/card/package.json
packages/checkbox/package.json
packages/chips/package.json
packages/drawer/package.json
packages/fab/package.json
packages/floating-label/package.json
packages/icon-button/package.json
packages/layout-grid/package.json
packages/line-ripple/package.json
packages/linear-progress/package.json
packages/list/package.json
packages/material-icon/package.json
packages/menu-surface/package.json
packages/notched-outline/package.json
packages/radio/package.json
packages/ripple/package.json
packages/select/package.json
packages/switch/package.json
packages/tab-bar/package.json
packages/tab-indicator/package.json
packages/tab-scroller/package.json
packages/tab/package.json
packages/text-field/package.json
packages/top-app-bar/package.json
packages/typography/package.json

fixes https://github.com/material-components/material-components-web-react/issues/567

fix(infrastructure): add declaration package.json

---

README.md
packages/webpack.config.js
scripts/release/cp-pkgs.js
tsconfig.json

The change to ts-loader increased the amount of memory the webpack config needed. Changing the webpack config to use the multiple entries pattern allows webpack to perform a lot faster.
BREAKING CHANGE: Remove `<package-name>.es.js` files. The alternate is now to use the `index.tsx` files.

fix(infrastructure): condense webpack configuration build step into one json file 

---

packages/ripple/index.tsx

This PR fixes #581.
I did not write any tests, as writing tests for SSR use cases is under consideration at #588.
The compiled result of the changed code is as follows, which should fix the regression seen in SSR projects:
```js
var HTMLElementShim = typeof HTMLElement === 'undefined' ? { } : HTMLElement;
var MATCHES = mdc_ripple_1.util.getMatchesProperty(HTMLElementShim.prototype);
```
I’m relatively new to writing TypeScript, so please let me know if `any` as a type should be changed.
Warm regards,
Anthony

fix(ripple): Adds HTMLElement shim to fix regression for SSR projects

---

packages/text-field/README.md
packages/text-field/icon/README.md
packages/text-field/icon/index.tsx
packages/text-field/index.tsx
test/screenshot/golden.json
test/screenshot/text-field/TextFieldPermutations.tsx
test/screenshot/text-field/attributesMap.tsx
test/screenshot/text-field/icon/index.tsx
test/unit/text-field/icon/index.test.tsx
test/unit/text-field/index.test.tsx

Implements missing icon adapter method `notifyIconAction` on `<Icon/>`. Accomplished via adding optional `onSelect` to `<Icon/>` and corresponding `onLeadingIconSelect` and `onTrailingIconSelect` on `<TextField/>`. Still having trouble with screenshot tests. Should close #585. 
Note: this is the first I've worked with typescript. 
---
I signed it

fix(text field): adds missing adapter method `notifyIconAction` on Icon 

---

packages/ripple/package.json

utility-types was not listed in the ripple/package.json file, which caused an issue when using a component with ripple.
Found when fixing https://github.com/material-components/material-components-web-react/issues/610

fix(ripple): add missing dependency to package.json

---

packages/dialog/README.md

Fix Dialog documentation. Example would not work properly because variable c had been renamed, but not changed in all places.Additionally, it was renamed to a variable that already existed.
> Note: I did not open an issue for this. I can if you prefer. 
---
I signed it

docs(dialog): Example variable choice already existed, and 'c' no longer did.

---

package.json

v2 uses outdated canvas, which does not build on latest Ubuntu

Upgrade resemblejs to v3

---

.travis.yml
docs/release.md
docs/screenshot-tests.md
package.json
test/screenshot/screenshot.tsx

What was changed:
1. Golden screenshots are downloaded with their public URL, not with GCS API. The comparison will become available for everyone
2. If there are no GSC token available, tests still compare screenshots with Golden but do not upload anything
3. travis.yml tests will run for every branch of every repository, not only for master of main repository
This means if no UI changes, screenshot tests will pass. Goldens will still need to be uploaded manually

Fix screenshot tests for external contributors and pull requests

---

packages/text-field/Input.tsx

This line imports constants module not from @material/textfield/dist, but from original source code
```
import {VALIDATION_ATTR_WHITELIST} from '@material/textfield/constants';
```
`@material/textfield/constants` is written in Babel language (I don't know how to call it) and contains babel export construction. If someone tries to use textfield from node.js test, it will fail
It is regression as it worked for version 0.7.0

Do not import constants from @material/textfield internals

---

packages/list/README.md

ListDivider should have `div` tag instead of default `li` when used outside of `<List>`

docs(list): fix ListDivider example

---

packages/chips/ChipSet.tsx
test/unit/chips/ChipSet.test.tsx

fixes chips when filter chips are unmounted. setCheckmarkWidth ref method is called, but `checkmark` is null.

fix(chips): null check for checkmark ref

---

package.json
packages/list/index.tsx
test/unit/list/index.test.tsx

Now ```<List />```checks children's type using ```isListItem```.
If parameter is null/undefined, an error occurs.
So I add code that checks element's existence.
p.s. I add one dependency(@material/radio) because there is error "cannot find module" when running test code. If you do not need it, I will revert it.

fix(list): renders a list with children which is not DOM

---

packages/button/index.tsx
test/unit/button/index.test.tsx

I've chosen to extend `React.AnchorHTMLAttributes<T>` and `React.ButtonHTMLAttributes<T>` since these are the possible element types that can be rendered. However looking through the other components you seem to use `HTMLProps<T>` a lot as well. There doesn't seem to be any clear reason why this is used in some places and not in others.
I'm happy to change this to use `HTMLProps<T>` instead if that is the pattern you want to follow. It would make button consistent with icon-button.

fix(button): Support anchor and button HTML attributes (#679)

---

scripts/release/cp-pkgs.js

fixes https://github.com/material-components/material-components-web-react/issues/681
Stop renaming `foo-package.js.map` to `index.js.map`. This is linked to the `dist/index.js`.

fix(infrastructure): fix source mappings under dist directory

---

packages/checkbox/index.tsx
test/unit/checkbox/index.test.tsx

This is a suggested interim solution until issue #438 can be resolved to be able to use Checkbox components in forms.

fix(checkbox): enable name attribute

---

packages/tab/index.tsx
test/unit/tab/index.test.tsx

Sets the initial state for the `tabIndex` the same way it is set for `aria-selected`. If a tab is active then the `activate` method on the foundation will update this state on mount.

fix(tab): Set initial tabIndex state to -1 (#690)

---

packages/chips/package.json

a fix for this error:
https://github.com/JedWatson/classnames/pull/106
was added in classnames v 2.2.6.
update dependency version from 2.2.5 to 2.2.6

update classnames version to 2.2.6

---

packages/ripple/index.tsx
packages/ripple/package.json
packages/tab-scroller/index.tsx
packages/tab-scroller/package.json

mdc-dom is implementing a `matches` method that wasn't used everywhere.
`getMatchesProperty()` will be removed in the next release of mdc-web by https://github.com/material-components/material-components-web/pull/4372.
It prevented some SSR usage of the material-components library.
This commit replaces `getMatchesProperty()` usage by `matches`.
It will partially resolve #654.

fix(ripple): Use mdc-dom.matches instead of `getMatchesProperty()`

---

packages/dialog/DialogContent.tsx
packages/dialog/DialogFooter.tsx
packages/dialog/DialogTitle.tsx
packages/dialog/index.tsx
test/unit/dialog/index.test.tsx

successful merge closes #696 
---
I signed it

fix(dialog): should extend HTMLElement

---

packages/select/NativeControl.tsx
packages/select/README.md
packages/select/index.tsx

successful merge should close #717
---
I signed it

fix(select): prop value should be string only

---

packages/tab/README.md
packages/tab/index.tsx
test/unit/tab/index.test.tsx

feat(tab): implement setFocusOnActivate

---

package.json
tsconfig.json

- strictNullChecks is set to true in `strict = true`, which is set in gts/tsconfig-google.json
- forceConsistentCasingInFileNames is set to true in gts/tsconfig-google.json
for reference
https://github.com/google/gts/blob/master/tsconfig-google.json

fix(infrastructure): remove duplicate tsconfig properties

---

packages/switch/package.json

This dependency isn't being used and, with the next release, this package would break when doing SSR because this version of `@material/ripple` contains direct reference to `HTMLElement`.

chore(switch): remove unused mdcw-ripple dep

---

packages/list/ListItem.tsx
packages/ripple/index.tsx

related https://github.com/material-components/material-components-web-react/pull/737
fixes https://github.com/material-components/material-components-web-react/issues/734
ListItem was missed as the changes were made in the MDC Web v1 typescript update. We moved the list changes out of the latest release, which included making these optional.

fix(list): make listitem props optional

---

package-lock.json
package.json
packages/radio/index.tsx
packages/radio/package.json
test/unit/radio/index.test.tsx

feat(radio): upgrade to typescript v1

---

package.json
packages/typography/package.json

fix(typography): upgrade to mdc-web v1

---

package-lock.json
package.json
packages/dialog/index.tsx
packages/dialog/package.json
test/unit/dialog/index.test.tsx

fix(dialog): mdc-web v1 upgrade

---

package-lock.json
package.json
packages/top-app-bar/index.tsx
packages/top-app-bar/package.json
test/unit/top-app-bar/index.test.tsx

fix(top-app-bar): mdc-web v1 upgrade

---

package-lock.json
package.json
packages/icon-button/index.tsx
packages/icon-button/package.json
test/unit/icon-button/index.test.tsx

fix(icon-button): upgrade to mdc-web v1.1

---

packages/drawer/package.json

Currently the drawer and dialog components use different focus-trap versions. This
pull request syncs them to the later one (^4.0.2)
https://github.com/material-components/material-components-web-react/issues/795

chore(drawer): Update focus-trap dependency to ^4.0.2

---

packages/ripple/README.md

Hello, there is an error in this documentation. At line 23, reader is advised to add:
```js
@import "@material/ripple/index.scss";
```
This file does not exist.
User should be advised to add:
```js
@import "@material/ripple/mdc-ripple.scss";
```
Thank you
a

Correction to README file

---

packages/webpack.config.js

Remove MDCTextfield Constant External from webpack.config.js
fixes #802

fix: Remove MDCTextfield Constant External

---

packages/drawer/index.tsx
packages/drawer/package.json
packages/list/index.tsx
test/screenshot/golden.json
test/screenshot/text-field/variants.tsx

fix(drawer): add missing foundation import in drawer

---

package-lock.json
package.json
packages/select/Option.tsx
packages/select/package.json
test/screenshot/golden.json
test/screenshot/text-field/variants.tsx
test/unit/select/Option.test.tsx

feat(select): add option component

---

package.json
packages/select/helper-text/README.md
packages/select/helper-text/index.tsx
packages/select/package.json
test/screenshot/golden.json
test/screenshot/text-field/variants.tsx
test/unit/select/helper-text/index.test.tsx

feat(select): add helper text

---

package.json
packages/select/icon/README.md
packages/select/icon/index.tsx
packages/select/package.json
test/screenshot/golden.json
test/screenshot/text-field/variants.tsx
test/unit/select/icon/index.test.tsx

feat(select): add icon

---

package.json
packages/list/index.tsx

`memoize-one` cannot be resolved because of how it exports it's files. This lead to unit test failures. Also when running `npm run build`, the `clean` step would delete the `memoize-one/dist/` directory, resulting in a build failure.

fix(list): memoize-one build

---

packages/text-field/Input.tsx
packages/text-field/index.tsx
test/unit/text-field/index.test.tsx

 feat(text-field): Sync inputComponent when component is updated

---

packages/fab/index.tsx

Reopening #810 
> This PR is a follow up to this conversation: b62c36f#r33164756
> 
> `initRipple` and `unbounded` props should be optional.

fix(fab): Made initRipple and unbounded props optional

---

packages/chips/Chip.tsx
packages/tab-indicator/index.tsx
packages/tab-scroller/index.tsx

Fixes #853.
@moog16 I copied the usage from `ripple` and `tab-bar` so that it'd be easier to do a find & replace in the future.
Let me know if there's anything else I need to do.

fix: ClientRect/DOMRect is not IE11 compatible

---

package-lock.json
package.json
packages/chips/ChipSet.tsx
packages/chips/package-lock.json
packages/chips/package.json
test/unit/chips/ChipSet.test.tsx

fix(chips): error with undefined or null children

---

.eslintrc.json

chore: set prettier to error lint

---

packages/text-field/Input.tsx
packages/text-field/README.md
packages/text-field/index.tsx
test/unit/text-field/Input.test.tsx
test/unit/text-field/index.test.tsx

fixes #895
**breaking changes**
`handleValueChange` is removed from Input's props.

fix(text-field): label isn't float when set value with setState

---

packages/ripple/index.tsx
test/unit/ripple/index.test.tsx

[Bug]: Ripple does not activate when clicked if it was previously activated with touch
fixes: #931

(fix:ripple) not activating when clicked after touch

---

packages/ripple/index.tsx
test/unit/ripple/index.test.tsx

fixes #916
@poying
I wrote it pretty much like your code.
But I'm not call `handleBlur` and I made `disabledRipplePostProcessor`.
Because there are some possibility that adds other code in`handleBlur`.
If you have any other opinion, tell me about that!
@moog16 
I added `adapter` to a member variable.
Existing member variables do not have an `adapter`, is there any special reason??
If both of you are okay, I'll write unit test code :)

fix(ripple): focus style alive when disabled

---

packages/linear-progress/README.md

fix(linear-progress): bufferingDots's default value is `true`
